notARepository: 'skip'
promptToReturnFromSubprocess: false
gui:
  nerdFontsVersion: "3"
keybinding:
  files:
    viewResetOptions: 'G'
  commits:
    viewResetOptions: 'G'
git:
  pagers:
    - colorArg: always
      pager: delta --dark --paging=never
